config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  resources :rooms do
    resources :messages
  end

  resources :users

  get '/search/:search_term', to: 'posts#search_post'

  get 'rooms', to: 'rooms#index'
  post 'rooms/create', to: 'rooms#create'
  post 'rooms/create_private', to: 'rooms#create_private'

  get 'contacts', to: 'contacts#index'
  post 'contacts/add', to: 'contacts#add'

  get 'posts', to: 'posts#index'
  post 'post', to: 'posts#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'log_in', to: 'sessions#login'
  post 'log_in', to: 'sessions#create'

  get 'sign_up', to: 'registrations#register'
  post 'sign_up', to: 'registrations#create'

  delete 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'home/index'
  root 'home#index'
end

app/views/shared/_contacts.html.erb
<%= javascript_include_tag "contacts.js" %>

<div class="contact-container">
  <div class="collapse-uncollapse"><a id="collapse-uncollapse" onclick="collapse()">▼</a></div>
  <div id="contacts-info">
    <ul id="contact-list" class="contact-list">
      <li>Contact</li>
      <li>Contact1</li>
      <li>Contact2</li>
      <li>Contact3</li>
      <li>Contact4</li>
      <li>Contact5</li>
      <li>Contact6</li>
      <li>Contact</li>
      <li>Contact1</li>
      <li>Contact2</li>
      <li>Contact3</li>
      <li>Contact4</li>
      <li>Contact5</li>
      <li>Contact6</li>
    </ul>
    <div class="add-contact"><a>Add Contact</a></div>
    <div>
      <input class="search-contact" type="text" oninput="this.setAttribute('value',this.value)" placeholder="Search for a contact...">
    </div>
  </div>
  <div id="Contacts">Contacts</div>
</div>

app/views/shared/_create_post.html.erb
<%= stylesheet_link_tag :post %>

<% if Current.user %>
  <div class="create-post">
    <%= form_with model: @post, url: post_path do |form| %>
      <section class="content">
        <%= form.text_area :content, class: 'form-control create-post-input', autofocus: true, placeholder: 'What\'s up?', cols: "30", rows: "15" %>
      </section>
      <div class="attach-to-post">
        <%= form.file_field :attachment, class: 'file-input form-control' %>
        <%= form.submit 'Post', class: 'post-button login-button btn btn-primary'%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm">
    <div class="container-fluid">
      <%= link_to 'ThreadVerse', root_path, class: "navbar-brand"%>
      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav w-100">
          <% if @is_search_bar == nil %>
            <li class="search-box mx-auto">
              <%= form_with url: "/search/:search_term", method: :get do |form| %>
                <%= form.text_field :content, class: "search-input", oninput: "this.setAttribute('value',this.value)" %>
                <%= form.button nil, class: "search-button" do %>
                  <i class="search-icon fa fa-search"></i>
                <% end %>
              <% end %>
            </li>
          <% end %>
          <li class="nav-item dropdown ms-auto mb-lg-8">
            <% if Current.user %>
              <div class="btn-group dropstart">
                <button type="button" class="login-button btn dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false"><%= Current.user.username %></button>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><button type="button" class="dropdown-item">Profile</button></li>
                  <li><%= link_to "Notifications", notifications_path, class: "dropdown-item" %></li>
                  <li><%= link_to "Change Password", edit_password_path, class: "dropdown-item" %></li>
                  <li><%= button_to "Log Out", logout_path, class: "dropdown-item", type: "button", method: :delete %></li>
                </ul>
              </div>
            <% else %>
              <%= link_to 'Log In', log_in_path, class: "login-button" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<% if Current.user %>
  <%= render partial: 'contacts/contacts' %>

  <!--<div class="messages-float">
    <div style="overflow: hidden;">
      <iframe class="messages-iframe" src="http://127.0.0.1:3000/users/5" scrolling="no"></iframe>
    </div>
  </div>-->

  <% if @single_room %>
    <div class="messages-float">
      <%= render partial: 'rooms/chat' %>
    </div>
  <% end %>

<% end %>