config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  resources :rooms do
    resources :messages
  end

  resources :users

  get '/search/:search_term', to: 'posts#search_post'

  get 'rooms', to: 'rooms#index'
  post 'rooms/create', to: 'rooms#create'
  post 'rooms/create_private', to: 'rooms#create_private'

  get 'contacts', to: 'contacts#index'
  post 'contacts/add', to: 'contacts#add'

  get 'posts', to: 'posts#index'
  post 'post', to: 'posts#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'log_in', to: 'sessions#login'
  post 'log_in', to: 'sessions#create'

  get 'sign_up', to: 'registrations#register'
  post 'sign_up', to: 'registrations#create'

  delete 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'home/index'
  root 'home#index'
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  # Get /contacts
  def index
    @users = User.all_except(Current.user.followers)
  end

  # Post /contacts/add
  def add
    user = User.find(params[:user_id])

    return unless user.present?

    @relationship = Relationship.create!(
      followee_id: Current.user.id,
      follower_id: user.id
    )

    if @relationship.save
      redirect_to root_path, notice: 'Contact saved.'
    else
      redirect_to root_path, alert: 'Something went wrong, the contact was not saved.'
    end
  end
end

app/views/contacts/_contact.html.erb
<% if contact.id != Current.user.id %>
  <div>
    <%= form_with url: contacts_add_path do |form| %>
      <%= form.hidden_field :user_id, :value => contact.id %>
      <%= form.submit contact.username, class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/contacts/_contacts.html.erb
<%= javascript_include_tag "contacts.js" %>

<div class="contact-container">
  <div class="collapse-uncollapse"><a id="collapse-uncollapse" onclick="collapse()">▼</a></div>
  <div id="contacts-info" style="display: block;">
    <ul id="contact-list" class="contact-list">
      <div>Contact</div>
      <% Current.user.followers.each do |contact| %>
        <li>
          <%= render contact %>
        </li>
      <% end %>
      <div class="group-chat-list">Groups</div>
      <% Room.get_all_groups_of_user(Current.user).each do |r| %>
        <li class="group-chat-list-item">
          <%= link_to r.name, r, class: "group-chat-list-item-btn btn"%>
        </li>
      <% end %>
    </ul>
    <div class="add-contact"><%= link_to "Add Contact", contacts_path, class: "add-contacts-link" %></div>
    <div>
      <input class="search-contact" type="text" oninput="this.setAttribute('value',this.value)" placeholder="Search for a contact...">
    </div>
  </div>
  <div id="Contacts">Contacts</div>
</div>

app/views/contacts/index.html.erb
<%= stylesheet_link_tag :contacts %>

<div id="users">
  <% @users.each do |user| %>
    <div><%= render partial: "contacts/contact", locals: { contact: user} %></div>
  <% end %>
</div>