config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  resources :rooms do
    resources :messages
  end

  resources :users

  get '/search/:search_term', to: 'posts#search_post'

  get 'rooms', to: 'rooms#index'
  post 'rooms/create', to: 'rooms#create'
  post 'rooms/create_private', to: 'rooms#create_private'

  get 'contacts', to: 'contacts#index'
  post 'contacts/add', to: 'contacts#add'

  get 'posts', to: 'posts#index'
  post 'post', to: 'posts#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'log_in', to: 'sessions#login'
  post 'log_in', to: 'sessions#create'

  get 'sign_up', to: 'registrations#register'
  post 'sign_up', to: 'registrations#create'

  delete 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'home/index'
  root 'home#index'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates_uniqueness_of :name

  scope :public_rooms, -> { where(is_private: false) }

  # after_create_commit { broadcast_append_to 'rooms' }
  # after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to 'rooms' unless is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

  def self.get_all_groups_of_user(user)
    @all_rooms = Room.joins(:participants).where(participants: { user_id: user.id }).select('rooms.*')
    @group_rooms = []
    @all_rooms.each do |r|
      @part = Participant.where(room_id: r.id).count
      @group_rooms << r if @part > 2
    end
    @group_rooms
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  def index
    redirect_to sign_up_path unless Current.user
    @rooms = Room.public_rooms
    @users = Current.user.followers
  end

  def create
    @room = Room.create!(name: params['name'])

    if @room.save
      redirect_to rooms_path, notice: 'Room created.'
    else
      redirect_to root_path, alert: 'Something went wrong, the room was not created.'
    end
  end

  def create_private
    @parts = []
    @parts << Current.user if Current.user
    Current.user.followers.each do |u|
      u_username = u.username
      if params[u_username] == '1'
        get_user = User.find_by(id: u.id)
        @parts << get_user if get_user
      end
    end

    if @parts.count <= 2
      redirect_to root_path,
                  alert: 'You need to add more users to the room, the room was not created.'
    end

    get_name(@parts)
    @room = Room.create_private_room(@parts, @room_name)

    if @room.save
      redirect_to @room, notice: 'Room created.'
    else
      redirect_to root_path, alert: 'Something went wrong, the room was not created.'
    end
  end

  def show
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = Current.user.followers
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages
    @room_name = @single_room.name

    @posts = Post.all
    @post = Post.new

    render 'home/index'
  end

  private

  def get_name(users)
    users = users.sort
    @room_name = 'private_'

    users.each do |u|
      @room_name = "#{@room_name}_#{u.id}"
    end
  end
end

app/views/rooms/_add_user_list.html.erb
<%= javascript_include_tag "rooms.js" %>

<div id="add-user-content" style="display: none;">
    <%= form_with url: rooms_create_private_path do |f| %>
        <% Current.user.followers.each do |contact| %>
            <% if contact.id != @user.id %>
                <div class="checkbox-box">
                    <%= f.check_box contact.username %>
                    <%= f.label contact.username, contact.username %>
                </div>
            <% else %>
                <%= f.hidden_field contact.username, :value => "1" %>
            <% end %>
        <% end %>
        <%= f.button nil, class: "add-button btn btn-dark" do %>
            <i class="fa fa-plus"></i>
        <% end %>
    <% end %>
</div>

app/views/rooms/_chat.html.erb
<%= stylesheet_link_tag :rooms %>
<%= javascript_include_tag "rooms.js" %>

<% if @single_room %>
    <div class="row">
        <div id="current-room" class="message-room bg-dark text-light">
            <div class="room-title">
                <h4 class="text-center">
                    <%= @user&.username || @single_room.name %>
                    <% if @user %>
                        <button id="add-user-button" class="add-user-button btn btn-dark" onclick="addUser()"><i class="fa fa-user-plus"></i></Button>
                    <% end %>
                </h4>
                <% if @user %>
                    <%= render partial: 'rooms/add_user_list' %>
                <% end %>
            </div>
            <%= turbo_stream_from @single_room %>
            <div id="messages">
                <%= render @messages %>
            </div>
            <%= render partial: 'messages/new_message_form' %>
        </div>
    </div>
<% end %>

app/views/rooms/_new_room_form.html.erb
<%= form_with model: @room, url: rooms_create_path, class: "d-flex new-room-form" do |form| %>
  <div>
    <%= form.text_field :name, class: "new-room-input form-control", autocomplete: 'off' %>
  </div>
  <br><br><br><br><br>
  <div class="create-room-button-div">
    <%= form.submit "Create Room", data: { disable_with: false }, class: "login-button btn"%>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room, class: "room-list-li" %>
</div>

app/views/rooms/index.html.erb
<%= stylesheet_link_tag :rooms %>
<%= javascript_include_tag "rooms.js" %>

<style>
  body {
      overflow: hidden;
  }
</style>

<div class="row">
  <div class="contact-and-room-list col-md-3">
    <div class="go-to-home">
      <%= link_to "Home", root_path, class: "login-button btn" %>
    </div>
    <h4> Contacts </h4>
    <div>
      <%= turbo_stream_from "users" %>
      <div id="users" class="contacts-info">
        <ul class="contact-list contact-list-room">
          <%= render @users %>
        </ul>
      </div>
    </div>
    <h4> Rooms </h4>
    <%= render partial: 'rooms/new_room_form' %>
    <div>
      <%= turbo_stream_from "rooms" %>
      <div id="rooms">
        <ul class="contact-list contact-list-room">
          <%= render @rooms %>
        </ul>
      </div>
    </div>
  </div>
  <div id="current-room" class="message-room col-md-9 bg-dark text-light">
    <% if @single_room %>
      <div class="room-title">
        <h4 class="text-center"><%= @user&.username || @single_room.name %></h4>
      </div>
      <%= turbo_stream_from @single_room %>
      <div id="messages">
        <%= render @messages %>
      </div>
      <%= render partial: 'messages/new_message_form' %>
    <% end %>
  </div>
</div>