config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'

  resources :rooms do
    resources :messages
  end

  resources :users

  get '/search/:search_term', to: 'posts#search_post'

  get 'rooms', to: 'rooms#index'
  post 'rooms/create', to: 'rooms#create'
  post 'rooms/create_private', to: 'rooms#create_private'

  get 'contacts', to: 'contacts#index'
  post 'contacts/add', to: 'contacts#add'

  get 'posts', to: 'posts#index'
  post 'post', to: 'posts#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'log_in', to: 'sessions#login'
  post 'log_in', to: 'sessions#create'

  get 'sign_up', to: 'registrations#register'
  post 'sign_up', to: 'registrations#create'

  delete 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'home/index'
  root 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :attachment, AvatarUploader
  belongs_to :user
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1/edit
  def edit; end

  def search_post
    @posts = Post.where('lower(content) like ?', "%#{params[:content].downcase}%")
    puts @posts
    render 'home/index'
  end

  # POST /posts
  def create
    @post = Post.new(post_params) do |post|
      post.user = Current.user
    end

    if @post.save
      redirect_to root_path, notice: 'Post uploaded successfully'
    else
      redirect_to root_path, alert: 'Post could not be uploaded'
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:attachment, :content, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_create_post.html.erb
<%= stylesheet_link_tag :post %>

<% if Current.user %>
  <div class="create-post">
    <%= form_with model: @post, url: post_path do |form| %>
      <section class="content">
        <%= form.text_area :content, class: 'form-control create-post-input', autofocus: false, placeholder: 'What\'s up?', cols: "30", rows: "15" %>
      </section>
      <div class="attach-to-post">
        <%= form.file_field :attachment, class: 'file-input form-control' %>
        <%= form.submit 'Post', class: 'post-button login-button btn btn-primary'%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :attachment, style: "display: block" %>
    <%= form.text_field :attachment %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag :post %>

<% if post %>
  <div class="middle-of-screen">
    <div class="card" id="<%= dom_id post %>">
      <div class="top">
        <div class="user_details">
          <h3><%= post.user.username %>
            <br>
              <span class="hour">
                <%= post.created_at.in_time_zone(+2).strftime("Posted on %B %d, %Y at %H:%M") %>
              </span>

          </h3>
        </div>
      </div>
      <h4 class="message"><%= post.content %></h4>
      <% if post.attachment? %>
        <div class="imgBg">
          <img src="<%= post.attachment %>" alt="posted-image" class="coverFull">
        </div>
      <% end %>
      <div class="btns">
      </div>
      <div class="border"></div>
    </div>
  </div>  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>